version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: GestionMicroEscolar/Dockerfile
    container_name: gestionmicroescolar
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: micros_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"
    volumes:
      - micros_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  micros_data:
